import { GraduationCap, BookOpen, Award} from "lucide-react";

export const educationData = [
  {
    id: 1,
    level: "SSC",
    fullTitle: "Secondary School Certificate",
    year: "2020",
    gpa: "4.22",
    outOf: "5.00",
    status: "Completed",
    icon: <BookOpen size={22} />,
    gradient: "from-blue-500 to-cyan-400",
    glowColor: "shadow-blue-500/20",
    borderColor: "border-blue-500/30",
    badgeColor: "bg-blue-500/10 text-blue-400 border-blue-500/20",
    highlight: "Strong Foundation",
    description: "Completed SSC with a solid academic foundation in science and core subjects.",
  },
  {
    id: 2,
    level: "HSC",
    fullTitle: "Higher Secondary Certificate",
    year: "2022",
    gpa: "4.17",
    outOf: "5.00",
    status: "Completed",
    icon: <Award size={22} />,
    gradient: "from-purple-500 to-pink-500",
    glowColor: "shadow-purple-500/20",
    borderColor: "border-purple-500/30",
    badgeColor: "bg-purple-500/10 text-purple-400 border-purple-500/20",
    highlight: "Advanced Studies",
    description: "Excelled in higher secondary with a consistent GPA across all subjects.",
  },
  {
    id: 3,
    level: "B.Sc",
    fullTitle: "Bachelor of Science (Running)",
    year: "2022 — Present",
    gpa: "Running",
    outOf: null,
    status: "3rd Year",
    icon: <GraduationCap size={22} />,
    gradient: "from-emerald-500 to-teal-400",
    glowColor: "shadow-emerald-500/20",
    borderColor: "border-emerald-500/30",
    badgeColor: "bg-emerald-500/10 text-emerald-400 border-emerald-500/20",
    highlight: "Currently Enrolled",
    description: "Pursuing B.Sc in Social Work, currently in the 3rd year with a focus on social welfare, community development, and human behavior.",
  },
];