import { FaCss3Alt, FaPython } from "react-icons/fa";
import {
  SiReact,
  SiNextdotjs,
  SiJavascript,
  SiTailwindcss,
  SiRedux,
  SiNodedotjs,
  SiExpress,
  SiMongodb,
  SiGit,
  SiDocker,
  SiFirebase,
  SiPrisma,
  SiVercel,
  SiFigma,
  SiTypescript,
  SiFramework,
} from "react-icons/si";

export const columns = [
  {
    title: "Frontend & UI/UX",
    subtitle: "Building fast, interactive user interfaces",
    skills: [
      {
        name: "Next.js",
        icon: <SiNextdotjs />,
        percentage: "90%",
        color: "linear-gradient(90deg,#e0e0e0,#a0a0a0)",
        iconColor: "#e2e8f0",
      },
      {
        name: "React",
        icon: <SiReact />,
        percentage: "95%",
        color: "linear-gradient(90deg,#1a9ed4,#61dafb)",
        iconColor: "#61DAFB",
      },
      {
        name: "Tailwind CSS",
        icon: <SiTailwindcss />,
        percentage: "98%",
        color: "linear-gradient(90deg,#0ea5e9,#06b6d4)",
        iconColor: "#38bdf8",
      },
      {
        name: "CSS",
        icon: <FaCss3Alt />,
        percentage: "92%",
        color: "linear-gradient(90deg,#2965f1,#264de4)",
        iconColor: "#60a5fa",
      },
      {
        name: "Redux",
        icon: <SiRedux />,
        percentage: "80%",
        color: "linear-gradient(90deg,#764abc,#c084fc)",
        iconColor: "#c084fc",
      },
      {
        name: "UI Component Libraries",
        icon: <SiFramework />,
        percentage: "80%",
        color: "linear-gradient(90deg,#6366f1,#a78bfa)",
        iconColor: "#a78bfa",
      },
    ],
  },
  {
    title: "Backend & Auth",
    subtitle: "Designing scalable server-side systems",
    skills: [
      {
        name: "Node.js",
        icon: <SiNodedotjs />,
        percentage: "90%",
        color: "linear-gradient(90deg,#3c873a,#68a063)",
        iconColor: "#86efac",
      },
      {
        name: "MongoDB",
        icon: <SiMongodb />,
        percentage: "85%",
        color: "linear-gradient(90deg,#116149,#47a248)",
        iconColor: "#4ade80",
      },
      {
        name: "Express",
        icon: <SiExpress />,
        percentage: "88%",
        color: "linear-gradient(90deg,#525252,#a3a3a3)",
        iconColor: "#d4d4d4",
      },
      {
        name: "Firebase",
        icon: <SiFirebase />,
        percentage: "80%",
        color: "linear-gradient(90deg,#f59e0b,#ef4444)",
        iconColor: "#fbbf24",
      },
      {
        name: "BetterAuth",
        icon: <SiFirebase />,
        percentage: "95%",
        color: "linear-gradient(90deg,#0891b2,#6366f1)",
        iconColor: "#67e8f9",
      },
      {
        name: "Prisma",
        icon: <SiPrisma />,
        percentage: "70%",
        color: "linear-gradient(90deg,#0f172a,#3b82f6)",
        iconColor: "#93c5fd",
      },
    ],
  },
  {
    title: "Tools & Platforms",
    subtitle: "DevOps, cloud, and productivity tools",
    skills: [
      {
        name: "Git",
        icon: <SiGit />,
        percentage: "92%",
        color: "linear-gradient(90deg,#c0392b,#f05032)",
        iconColor: "#fca5a5",
      },
      {
        name: "Vercel",
        icon: <SiVercel />,
        percentage: "90%",
        color: "linear-gradient(90deg,#1a1a2e,#e2e8f0)",
        iconColor: "#f8fafc",
      },
      {
        name: "Docker",
        icon: <SiDocker />,
        percentage: "78%",
        color: "linear-gradient(90deg,#1d63ed,#00b4d8)",
        iconColor: "#7dd3fc",
      },
      {
        name: "Figma",
        icon: <SiFigma />,
        percentage: "85%",
        color: "linear-gradient(90deg,#f24e1e,#a259ff)",
        iconColor: "#fb923c",
      },
    ],
  },
  {
    title: "Core & Language",
    subtitle: "Developing the logic and fundamental structure of an application.",
    skills: [
      {
        name: "JavaScript",
        icon: <SiJavascript />,
        percentage: "95%",
        color: "linear-gradient(90deg,#ca8a04,#f7df1e)",
        iconColor: "#fde047",
      },
      {
        name: "TypeScript (exploring)",
        icon: <SiTypescript />,
        percentage: "50%",
        color: "linear-gradient(90deg,#1d4ed8,#3178c6)",
        iconColor: "#93c5fd",
      },
      {
        name: "Python (exploring)",
        icon: <FaPython />,
        percentage: "50%",
        color: "linear-gradient(90deg,#3b82f6,#facc15)",
        iconColor: "#fde68a",
      },
    ],
  },
];