// constants/projects.js ফাইল

export const allProjects = [
  {
    id: 1,
    title: "Looklify – Beauty E-Commerce",
    description: "Built with Next.js and MongoDB.",
    fullDescription: "Detailed info about Looklify project...",
    tags: ["Next.js", "MongoDB"],
    category: "Full Stack",
    image: "/project1.png", 
    liveLink: "https://looklify.vercel.app",
  },
  {
    id: 2,
    title: "CareerOstad – AI Platform",
    description: "AI-powered job matching system.",
    fullDescription: "Detailed info about CareerOstad...",
    tags: ["Next.js", "Tailwind"],
    category: "Full Stack",
    image: "/project2.png", 
    liveLink: "https://careerostad.vercel.app",
  },
  {
    id: 3,
    title: "CareerOstad – AI Platform",
    description: "AI-powered job matching system.",
    fullDescription: "Detailed info about CareerOstad...",
    tags: ["Next.js", "Tailwind"],
    category: "Full Stack",
    image: "/project2.png", 
    liveLink: "https://careerostad.vercel.app",
  },
  {
    id: 4,
    title: "CareerOstad – AI Platform",
    description: "AI-powered job matching system.",
    fullDescription: "Detailed info about CareerOstad...",
    tags: ["Next.js", "Tailwind"],
    category: "Full Stack",
    image: "/project2.png", 
    liveLink: "https://careerostad.vercel.app",
  },
  {
    id: 5,
    title: "CareerOstad – AI Platform",
    description: "AI-powered job matching system.",
    fullDescription: "Detailed info about CareerOstad...",
    tags: ["Next.js", "Tailwind"],
    category: "Full Stack",
    image: "/project2.png", 
    liveLink: "https://careerostad.vercel.app",
  },
  {
    id: 6,
    title: "CareerOstad – AI Platform",
    description: "AI-powered job matching system.",
    fullDescription: "Detailed info about CareerOstad...",
    tags: ["Next.js", "Tailwind"],
    category: "Full Stack",
    image: "/project2.png", 
    liveLink: "https://careerostad.vercel.app",
  },
  {
    id: 7,
    title: "CareerOstad – AI Platform",
    description: "AI-powered job matching system.",
    fullDescription: "Detailed info about CareerOstad...",
    tags: ["Next.js", "Tailwind"],
    category: "Full Stack",
    image: "/project2.png", 
    liveLink: "https://careerostad.vercel.app",
  },
  {
    id: 8,
    title: "CareerOstad – AI Platform",
    description: "AI-powered job matching system.",
    fullDescription: "Detailed info about CareerOstad...",
    tags: ["Next.js", "Tailwind"],
    category: "Full Stack",
    image: "/project2.png", 
    liveLink: "https://careerostad.vercel.app",
  },
  {
    id: 9,
    title: "CareerOstad – AI Platform",
    description: "AI-powered job matching system.",
    fullDescription: "Detailed info about CareerOstad...",
    tags: ["Next.js", "Tailwind"],
    category: "Full Stack",
    image: "/project2.png", 
    liveLink: "https://careerostad.vercel.app",
  },
  {
    id: 10,
    title: "CareerOstad – AI Platform",
    description: "AI-powered job matching system.",
    fullDescription: "Detailed info about CareerOstad...",
    tags: ["Next.js", "Tailwind"],
    category: "Full Stack",
    image: "/project2.png", 
    liveLink: "https://careerostad.vercel.app",
  },
];